# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-11 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='slider',
            managers=[
            ],
        ),
    ]
