# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='分类ID')),
                ('img', models.ImageField(upload_to='classify', verbose_name='分类主图')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mall.Classify')),
            ],
            options={
                'db_table': 'mall_classify',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='标签ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='tags', verbose_name='主图')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'mall_tag',
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-reorder']},
        ),
        migrations.AddField(
            model_name='product',
            name='buy_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='购买链接'),
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default='1', verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='简单描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=11, upload_to='product', verbose_name='主图'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_price',
            field=models.FloatField(default=11, verbose_name='原价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=11, verbose_name='兑换价格(积分兑换)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='remain_count',
            field=models.IntegerField(default=0, verbose_name='剩余库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder',
            field=models.SmallIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.FloatField(default=10.0, verbose_name='商品的评分'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku_count',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(11, '销售中'), (12, '已售完'), (13, '已下架')], default=12, verbose_name='商品状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.SmallIntegerField(choices=[(11, '实物商品'), (12, '虚拟商品')], default=11, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='商品名称'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='mall_product',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mall.Tag', verbose_name='标签'),
        ),
    ]
