# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-11 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200511_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
