# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-09 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=32, verbose_name='学生姓名')),
            ],
            options={
                'db_table': 'grade_student',
            },
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student_name',
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Student'),
        ),
    ]
