# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-10 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20200509_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_grade', to='grade.Student'),
        ),
    ]
