# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-08 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_student_id_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
