# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20200508_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('phone', models.CharField(max_length=11, verbose_name='收件人电话')),
                ('address', models.CharField(max_length=64, verbose_name='收件人地址')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮编')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.Student', verbose_name='学生')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=256, verbose_name='座右铭')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oauth.Student')),
            ],
        ),
    ]
