# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-09 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibouser',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '限制用户'), (1, '正常'), (0, '删除')], default=1, verbose_name='用户状态'),
        ),
    ]
