# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-09 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0002_weibouser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibouser',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='用户的创建时间'),
        ),
        migrations.AddField(
            model_name='weibouser',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注信息'),
        ),
    ]
